apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-app
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: vulnerable-app