name: Security Attack Pipeline

on:
  workflow_dispatch:

env:
  TARGET_SECURITY_APP: "http://dvwa-security:80"
  TARGET_VULNERABLE_APP: "http://dvwa-vulnerable:80"
  RESULTS_DIR: "/reports"
  ATTACKER_IMAGE: "andres2000gb/coverage-ktd:latest"

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull Attacker Image
        run: docker pull ${{ env.ATTACKER_IMAGE }}

      - name: Run Attacker
        run: |
          docker run --name attacker \
            -e TARGET_SECURITY_APP="${{ env.TARGET_SECURITY_APP }}" \
            -e TARGET_VULNERABLE_APP="${{ env.TARGET_VULNERABLE_APP }}" \
            ${{ env.ATTACKER_IMAGE }}

      - name: Copy results from container
        run: |
          mkdir -p ./local-results
          docker cp attacker:${{ env.RESULTS_DIR }}/ ./local-results/

      - name: Upload Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-attack-results
          path: ./local-results/*